#!/usr/bin/env php
<?php

// Fixes the permissions of attachments

require_once('include/cli_startup.php');

cli_startup();

switch ($argc) {
	case 3:
		if($argv[1]==='fix' and is_numeric($argv[2]))
			$action = $argv[1];
			$channel_id = intval($argv[2]);
			break;
	case 2:
		if($argv[1]==='list') {
			$action = $argv[1];
			break;
		}
	default:
		echo "Usage: $argv[0] (list|fix [uid])\nNothing happens...\n";
		return;
}

fix_all_attach($channel_id,$action);

function fix_all_attach($channel_id,$action){
	$r= q("select hash from attach where uid=%d",
		intval($channel_id)
		);
	foreach( $r as $rr ){
		$hash=$rr['hash'];
		$s=q("select allow_cid,deny_cid,allow_gid,deny_gid from item where uid=%d and attach like '%%%s%%'",
			intval($channel_id),
			dbesc($hash)
			);

		if($s===false){ echo "error: $hash item query error\n"; continue; }
		if(count($s)!=1) { echo "warning: $hash file in zero or multiple posts: " . count($s) . "\n"; continue; }

		if($action==='list'){
			echo $hash ." ". $s[0]['allow_cid'] ." ". $s[0]['deny_cid'] ." ". $s[0]['allow_gid'] ." ". $s[0]['deny_gid'] ."\n";
		}
		if($action==='fix'){
			$t=q("update attach set allow_cid='%s', deny_cid='%s', allow_gid='%s', deny_gid='%s' where hash='%s' and uid=%d",
				dbesc($s[0]['allow_cid']),
				dbesc($s[0]['deny_cid']),
				dbesc($s[0]['allow_gid']),
				dbesc($s[0]['deny_gid']),
				dbesc($hash),
				intval($channel_id)
				);
			if ($t) echo "Win!\n" ; else "Oops!\n";
		}
	}
}

