#!/usr/bin/env php
<?php

// Obscures or unobscures private posts.

require_once('include/cli_startup.php');

cli_startup();

switch ($argc) {
	case 3:
		if($argv[2]=='fuckyeah')
			$fuckyeah = true;
	case 2:
		if(in_array($argv[1],['obscure','unobscure'])) {
			$action = $argv[1];
			break;
		}
	default:
		echo "Choose either obscure or unobscure\n";
		return;
}

if($action == 'obscure') {
	$key = get_config('system','pubkey');
	if(! openssl_pkey_get_public($key)) {
		echo 'Error: Invalid pubkey!'. "\n";
		return;
	}
	$r = q("select id,title,body,item_flags from `item` where item_private>0 and not (item_flags & 0x1000) order by id");
	foreach($r as $rr){
		$id = $rr['id'];
		echo 'id: ' . $id . "\n";
		$item_flags = ( $rr['item_flags'] | ITEM_OBSCURED ) ;
		echo 'item_flags: ' . $rr['item_flags'] . ' -> ' . $item_flags . "\n";
		$title = json_encode(crypto_encapsulate($rr['title'],$key)) ;
		echo 'title: ' . $title . "\n" ;
		$body = json_encode(crypto_encapsulate($rr['body'],$key)) ;
		echo 'body: ' . $body . "\n" ;

		if($fuckyeah) {
			echo 'Fuck Yeah !' . "\n";
			q("update `item` set item_flags = %d, title = '%s', body = '%s' where id = %d",
			   intval($item_flags),
			   dbesc($title),
			   dbesc($body),
			   intval($id));
		}
	}
}
elseif($action == 'unobscure') {
	$key = get_config('system','prvkey');
	if(! openssl_pkey_get_private($key)) {
		echo 'Error: Invalid prvkey!'. "\n";
		return;
	}
	$r = q("select id,title,body,item_flags from `item` where item_private>0 and (item_flags & 0x1000) order by id");
	foreach($r as $rr){
		$id = $rr['id'];
		echo 'id: ' . $id . "\n";
		$item_flags = ( $rr['item_flags'] & ~ITEM_OBSCURED ) ;
		echo 'item_flags: ' . $rr['item_flags'] . ' -> ' . $item_flags . "\n";
		$title = crypto_unencapsulate(json_decode_plus($rr['title']),$key);
		echo 'title: ' . $title . "\n" ;
		$body = crypto_unencapsulate(json_decode_plus($rr['body']),$key);
		echo 'body: ' . $body . "\n" ;

		if($fuckyeah) {
			echo 'Fuck Yeah !' . "\n";
			q("update `item` set item_flags = %d, title = '%s', body = '%s' where id = %d",
			   intval($item_flags),
			   dbesc($title),
			   dbesc($body),
			   intval($id));
		}
	}
}

/*

select (item_flags & 0x1000),item_private,count(*) from `item` group by (item_flags & 0x1000),item_private;

select (item_flags & 0x1000),item_private,count(*) from `item` where (mid in (SELECT mid FROM `item` where item_flags & 0x1000)) group by (item_flags & 0x1000),item_private;

*/
